import { NextResponse } from 'next/server';
import { cookies } from 'next/headers';
import Stripe from 'stripe';
import { createClient } from '@supabase/supabase-js';

export async function GET(req: Request) {
  try {
    const { searchParams } = new URL(req.url);
    const interestId = searchParams.get('id');

    if (!interestId) {
      return NextResponse.json({ error: 'Missing interest ID' }, { status: 400 });
    }

    // Verify admin authentication
    const cookieStore = await cookies();
    const token = cookieStore.get('admin_auth_token');
    
    if (!token || token.value !== 'fully_authenticated_secret_token') {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const supabaseAdmin = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL || process.env.SUPABASE_URL || '',
      process.env.SUPABASE_SERVICE_ROLE_KEY || ''
    );

    // Get checkout session ID
    const { data: interestData, error: dbError } = await supabaseAdmin
      .from('interests')
      .select('checkout_session_id')
      .eq('id', interestId)
      .single();

    if (dbError || !interestData?.checkout_session_id) {
      return NextResponse.json({ error: 'Checkout session ID not found for this record' }, { status: 404 });
    }

    if (!process.env.STRIPE_SECRET_KEY) {
      return NextResponse.json({ error: 'Stripe configuration missing' }, { status: 500 });
    }

    const stripe = new Stripe(process.env.STRIPE_SECRET_KEY, {
      apiVersion: '2026-07-29.dahlia',
    });

    const session = await stripe.checkout.sessions.retrieve(interestData.checkout_session_id, {
      expand: ['invoice']
    });

    const invoice = session.invoice as Stripe.Invoice | null;

    if (!invoice || !invoice.invoice_pdf) {
      return NextResponse.json({ error: 'Invoice PDF not generated by Stripe yet' }, { status: 404 });
    }

    // Redirect the admin to the Stripe-hosted PDF
    return NextResponse.redirect(invoice.invoice_pdf);
    
  } catch (error: any) {
    console.error('Error fetching invoice:', error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
